// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftwareRouteur.Data;

#nullable disable

namespace SoftwareRouteur.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430123655_AddProfilesAndPinSupport")]
    partial class AddProfilesAndPinSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SoftwareRouteur.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("admin_users");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.BlockedTraffic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DstIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dst_ip");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("logged_at");

                    b.Property<string>("SrcIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("src_ip");

                    b.HasKey("Id");

                    b.ToTable("blocked_traffic");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<string>("OpnsenseAliasUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_alias_uuid");

                    b.Property<string>("OpnsenseRuleUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_rule_uuid");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.FirewallRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("destination");

                    b.Property<string>("OpnsenseAliasUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_alias_uuid");

                    b.Property<string>("OpnsenseRuleUuid")
                        .HasColumnType("longtext")
                        .HasColumnName("opnsense_rule_uuid");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rule_type");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("firewall_rules");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Monitoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveRules")
                        .HasColumnType("int")
                        .HasColumnName("active_rules");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("checked_at");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("client_ip");

                    b.Property<string>("Hostname")
                        .HasColumnType("longtext")
                        .HasColumnName("hostname");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_online");

                    b.HasKey("Id");

                    b.ToTable("monitoring");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("PinHash")
                        .HasColumnType("longtext")
                        .HasColumnName("pin_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Client", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Profile", "Profile")
                        .WithMany("Clients")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.FirewallRule", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Client", "Client")
                        .WithMany("FirewallRules")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Profile", b =>
                {
                    b.HasOne("SoftwareRouteur.Models.Profile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Client", b =>
                {
                    b.Navigation("FirewallRules");
                });

            modelBuilder.Entity("SoftwareRouteur.Models.Profile", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
